INPUT_USERNAME = 'css:[data-test="username"]'
INPUT_PASSWORD = 'css:[data-test="password"]'
LOGIN_BUTTON = 'css:[data-test="login-button"]'
ALERT_ERROR = 'css:h3[data-test="error"]'
ALERT_CONTAINER = '.error-message-container.error'
HOME_PAGE_LOGO = 'css:.app_logo'
INVENTORY_DIV = 'css:[data-test="inventory-item"]'
INVENTORY_ITEM = '//div[@class="inventory_item_name "][contains(.,"{}")]'
INVENTORY_ITEM_NAME = '//div[@data-test="inventory-item-name"][contains(.,"{}")]'
INVENTORY_ITEM_DESC = '//div[@data-test="inventory-item-desc"][contains(.,"{}")]'
INVENTORY_ITEM_PRICE = '//div[@data-test="inventory-item-price"][contains(.,"{}")]'
BTN_ADD_INVENTORY_TO_CART = '//button[contains(@data-test,"add-to-cart-{}")]'
BTN_REMOVE_INVENTORY_FROM_CART = '//button[contains(@data-test,"remove-{}")]'
BTN_ADD_ITEM_TO_CART = '//button[contains(@data-test,"add-to-cart")]'
BTN_REMOVE_ITEM_FROM_CART = '//button[contains(.,"Remove")]'
CART_BADGE= 'css:[data-test="shopping-cart-badge"]'
BTN_CONTINUE_SHOPPING= '//button[contains(@data-test,"continue-shopping")]'
BTN_CHECKOUT= '//button[contains(@data-test,"checkout")]'