INPUT_USERNAME = 'css:[data-test="username"]'
INPUT_PASSWORD = 'css:[data-test="password"]'
LOGIN_BUTTON = 'css:[data-test="login-button"]'
ALERT_ERROR = 'css:h3[data-test="error"]'
ALERT_CONTAINER = '.error-message-container.error'
HOME_PAGE_LOGO = 'css:.app_logo'
INVENTORY_DIV = 'css:[data-test="inventory-item"]'
INVENTORY_ITEM = '//div[@class="inventory_item_name "][contains(.,"{}")]'
INVENTORY_ITEM_NAME = '//div[@data-test="inventory-item-name"][contains(.,"{}")]'
INVENTORY_ITEM_DESC = '//div[@data-test="inventory-item-desc"][contains(.,"{}")]'
INVENTORY_ITEM_PRICE = '//div[@data-test="inventory-item-price"][contains(.,"{}")]'
BTN_BUY_INVENTORY = 'css:.btn.btn_primary.btn_small.btn_inventory'
BTN_BUY_INVENTORY_ITEM = 'css:[data-test="add-to-cart"]'