INPUT_USERNAME = 'css:[data-test="username"]'
INPUT_PASSWORD = 'css:[data-test="password"]'
LOGIN_BUTTON = 'css:[data-test="login-button"]'
ALERT_ERROR = 'css:h3[data-test="error"]'
ALERT_CONTAINER = '.error-message-container.error'
HOME_PAGE_LOGO = 'css:.app_logo'
INVENTORY_DIV = 'css:[data-test="inventory-item"]'
INVENTORY_ITEM = '//div[@class="inventory_item_name "][contains(.,"{}")]'
INVENTORY_ITEM_NAME = '//div[@data-test="inventory-item-name"][contains(.,"{}")]'
INVENTORY_ITEM_DESC = '//div[@data-test="inventory-item-desc"][contains(.,"{}")]'
INVENTORY_ITEM_PRICE = '//div[@data-test="inventory-item-price"][contains(.,"{}")]'
BTN_ADD_INVENTORY_TO_CART = 'css:.btn.btn_primary.btn_small.btn_inventory'
BTN_REMOVE_INVENTORY_FROM_CART = '//button[contains(@data-test,"remove-{}")]'
BTN_ADD_ITEM_TO_CART = '//button[contains(@data-test,"add-to-cart")]'
BTN_REMOVE_ITEM_FROM_CART = '//button[contains(.,"Remove")]'
CART_BADGE= 'css:[data-test="shopping-cart-badge"]'
BTN_CONTINUE_SHOPPING= '//button[contains(@data-test,"continue-shopping")]'
BTN_CHECKOUT= '//button[contains(@data-test,"checkout")]'
INPUT_NAME= 'css:[data-test="firstName"]'
INPUT_LAST_NAME= 'css:[data-test="lastName"]'
INPUT_ZIP_CODE= 'css:[data-test="postalCode"]'
CHECKOUT_SUCCESS_IMG= 'css:[data-test="pony-express"]'
CHECKOUT_PAYMENT_TITLE= 'css:[data-test="payment-info-label"]'
CHECKOUT_PAYMENT_DESCRIPTION= 'css:[data-test="payment-info-value"]'
CHECKOUT_SHIPPING_TITLE= 'css:[data-test="shipping-info-label"]'
CHECKOUT_SHIPPING_DESCRIPTION= 'css:[data-test="shipping-info-value"]'
CHECKOUT_PRICE_TOTAL_TITLE= 'css:[data-test="total-info-label"]'
CHECKOUT_ITEM_VALUE= 'css:[data-test="subtotal-label"]'
CHECKOUT_ITEM_TAX= 'css:[data-test="tax-label"]'
CHECKOUT_PRICE_TOTAL_VALUE= 'css:[data-test="total-label"]'
BTN_CONTINUE_CHECKOUT= 'css:[data-test="continue"]'
BTN_CANCEL_CHECKOUT= 'css:[data-test="cancel")]'
BTN_FINISH_CHECKOUT= '//button[contains(@data-test,"finish")]'
CHECKOUT_COMPLETE_TITLE= 'css:[data-test="complete-header"]'
CHECKOUT_COMPLETE_DESCRIPTION= 'css:[data-test="complete-text"]'
BTN_CHECKOUT_BACK_HOME= 'css:[data-test="back-to-products"]'